Fix: Refine backward compatibility of OpenCL version (#38)
* Fix: Refine backward compatibility of OpenCL version

* Fix: Give warning for compatibility check when configuration and remove SVM functions

* Note:
  Some of opnecl-headers version doesn't contain the API:
  clCreateProgramWithIL which is necessary now
  and result in obscure build fail message.

  This commit will check the function exist in configuration level
  and make warning as hint for developer.

  It might build fail with obscure message like:
  /home/pi/qpu/VC4CL/src/icd_loader.cpp:232:1: error: invalid conversion from ‘void ()(cl_context, void) {aka void ()(_cl_context, void*)}’ to ‘cl_int ()() {aka int ()()}’ [-fpermissive]